import FileManager from 'c/fileManager';
import { createElement } from '@lwc/engine-dom';

describe('c-file-manager', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const EXPECTED_RESULT = 1, element = createElement('c-file-manager', {
            is: FileManager
        });

        // Act
        document.body.appendChild(element);

        expect(EXPECTED_RESULT).toBe(EXPECTED_RESULT);
    });
});